# Generated by Django 4.0.5 on 2022-06-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('song', '0002_remove_user_last_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
